# Generated by Django 5.2.7 on 2025-10-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Activity Logs'},
        ),
    ]
