# Generated by Django 5.2.7 on 2025-10-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_maliciouskeyword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaliciousKeyword',
        ),
    ]
