# Generated by Django 5.2.7 on 2025-10-26 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_maliciouskeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(help_text='Unique scan identifier', max_length=255, unique=True)),
                ('domain', models.CharField(help_text='Domain being scanned', max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('scan_results_json', models.JSONField(blank=True, help_text='JSON results of the scan', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if scan failed', null=True)),
                ('user', models.ForeignKey(help_text='User who initiated the scan', on_delete=django.db.models.deletion.CASCADE, related_name='scan_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan History',
                'verbose_name_plural': 'Scan Histories',
                'ordering': ['-start_time'],
            },
        ),
    ]
