# Generated by Django 5.2.7 on 2025-10-29 07:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_scanhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainScanSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domain yang di-scan', max_length=255, unique=True)),
                ('total_cases', models.IntegerField(default=0, help_text='Total kasus malicious ditemukan')),
                ('hack_judol', models.IntegerField(default=0, help_text='Jumlah kasus hack/judol')),
                ('pornografi', models.IntegerField(default=0, help_text='Jumlah kasus pornografi')),
                ('hacked', models.IntegerField(default=0, help_text='Jumlah kasus hacked/defaced')),
                ('last_scan', models.DateTimeField(auto_now=True, help_text='Waktu scan terakhir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domain Scan Summary',
                'verbose_name_plural': 'Domain Scan Summaries',
                'ordering': ['-last_scan'],
            },
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='scan_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 29, 14, 32, 57, 182905), help_text='Tanggal scan dilakukan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='domain',
            field=models.CharField(help_text='Target domain yang di-scan', max_length=255),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='error_message',
            field=models.TextField(blank=True, help_text='Pesan error jika scan gagal', null=True),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='scan_id',
            field=models.CharField(help_text='Unique scan identifier', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='scan_results_json',
            field=models.TextField(blank=True, help_text='Hasil scan dalam format JSON', null=True),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
