# Generated by Django 5.2.7 on 2025-10-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_domainscansummary_scanhistory_scan_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanhistory',
            name='scan_date',
        ),
    ]
