# Generated by Django 5.2.7 on 2025-10-29 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_remove_scanhistory_scan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='scan_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Tanggal scan dilakukan'),
            preserve_default=False,
        ),
    ]
