# Generated by Django 5.2.7 on 2025-10-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_scanhistory_scan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Administrator'), ('superuser', 'Superuser')], default='user', help_text='Role pengguna untuk kontrol akses', max_length=20),
        ),
    ]
