# Generated by Django 5.2.7 on 2025-10-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='ran_with_verification',
            field=models.BooleanField(default=True, help_text='Apakah scan dijalankan dengan verifikasi real-time'),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='scan_type',
            field=models.CharField(default='Cepat (Google Only)', help_text='Tipe scan yang dilakukan (Cepat/Komprehensif)', max_length=50),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='showed_all_results',
            field=models.BooleanField(default=False, help_text='Apakah scan menampilkan semua hasil terindikasi (tanpa filter verifikasi)'),
        ),
    ]
