# Generated by Django 5.2.7 on 2025-11-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_scanhistory_ran_with_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maliciouskeyword',
            name='category',
            field=models.CharField(choices=[('judi', 'Judi Online'), ('pornografi', 'Pornografi'), ('hacking', 'Hacking/Malware'), ('phishing', 'Phishing'), ('narkoba', 'Narkoba/Obat Terlarang'), ('penipuan', 'Penipuan/Scam'), ('terorisme', 'Terorisme'), ('pemalsuan', 'Pemalsuan'), ('perdagangan_manusia', 'Perdagangan Manusia'), ('konten_kekerasan', 'Konten Kekerasan'), ('prostitusi', 'Prostitusi'), ('perjudian_ilegal', 'Perjudian Ilegal'), ('pornografi_anak', 'Pornografi Anak'), ('other', 'Lainnya')], default='other', help_text='Kategori keyword', max_length=20),
        ),
    ]
