# Generated by Django 5.2.7 on 2025-11-02 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_alter_maliciouskeyword_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_api_cache', models.BooleanField(default=True, help_text='Aktifkan caching hasil search (hemat 95% quota API)')),
                ('api_cache_ttl_days', models.IntegerField(default=7, help_text='Lama penyimpanan cache dalam hari (default: 7 hari)')),
                ('use_comprehensive_query', models.BooleanField(default=True, help_text='Gunakan query comprehensive (1 query vs 4 queries)')),
                ('max_search_results', models.IntegerField(default=100, help_text='Maksimal jumlah hasil search per query (default: 100)')),
                ('enable_bing_search', models.BooleanField(default=False, help_text='Aktifkan Bing search (menggunakan API key)')),
                ('enable_duckduckgo_search', models.BooleanField(default=True, help_text='Aktifkan DuckDuckGo search (GRATIS, no API key)')),
                ('enable_subdomain_dns_lookup', models.BooleanField(default=True, help_text='Aktifkan DNS lookup untuk subdomain (GRATIS)')),
                ('enable_subdomain_search', models.BooleanField(default=False, help_text='Aktifkan search subdomain via Google (menggunakan API)')),
                ('enable_subdomain_content_scan', models.BooleanField(default=False, help_text='Aktifkan scan konten subdomain (10+ API calls jika enable)')),
                ('max_subdomains_to_scan', models.IntegerField(default=10, help_text='Maksimal subdomain yang di-scan (default: 10)')),
                ('enable_deep_crawling', models.BooleanField(default=True, help_text='Aktifkan deep crawling untuk menemukan halaman tersembunyi')),
                ('enable_sitemap_analysis', models.BooleanField(default=True, help_text='Aktifkan analisis sitemap.xml (GRATIS)')),
                ('enable_path_discovery', models.BooleanField(default=True, help_text='Aktifkan path brute force discovery (GRATIS)')),
                ('enable_graph_analysis', models.BooleanField(default=True, help_text='Aktifkan graph analysis untuk orphan pages')),
                ('max_crawl_pages', models.IntegerField(default=50, help_text='Maksimal halaman yang di-crawl (default: 50)')),
                ('enable_realtime_verification', models.BooleanField(default=True, help_text='Aktifkan verifikasi real-time dengan Selenium')),
                ('use_tiered_verification', models.BooleanField(default=True, help_text='Gunakan tiered verification (requests first, then Selenium)')),
                ('enable_illegal_content_detection', models.BooleanField(default=True, help_text='Aktifkan deteksi konten ilegal komprehensif')),
                ('enable_hidden_content_detection', models.BooleanField(default=True, help_text='Aktifkan deteksi konten tersembunyi (CSS hidden, dll)')),
                ('enable_injection_detection', models.BooleanField(default=True, help_text='Aktifkan deteksi injeksi konten (JavaScript, iframe)')),
                ('enable_unindexed_discovery', models.BooleanField(default=True, help_text='Aktifkan discovery halaman tidak terindex Google')),
                ('enable_backlink_analysis', models.BooleanField(default=False, help_text='Aktifkan analisis backlink (menggunakan API)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Catatan admin tentang konfigurasi', null=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User terakhir yang mengupdate konfigurasi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
    ]
