# Generated by Django 5.2.7 on 2025-11-02 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_sistemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(help_text='Nama key (e.g., SERPAPI_MAIN, SERPAPI_FALLBACK)', max_length=100, unique=True)),
                ('key_value', models.CharField(help_text='Nilai API key (akan di-encrypt di production)', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Deskripsi penggunaan key ini')),
                ('is_active', models.BooleanField(default=True, help_text='Apakah key ini aktif digunakan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debug_mode', models.BooleanField(default=False, help_text='Debug mode (OFF di production!)')),
                ('allowed_hosts', models.TextField(default='localhost,127.0.0.1', help_text='Comma-separated list of allowed hosts')),
                ('csrf_cookie_secure', models.BooleanField(default=True, help_text='CSRF cookie secure flag')),
                ('session_cookie_secure', models.BooleanField(default=True, help_text='Session cookie secure flag')),
                ('secure_ssl_redirect', models.BooleanField(default=True, help_text='Force HTTPS redirect')),
                ('email_enabled', models.BooleanField(default=False, help_text='Enable email notifications')),
                ('email_host', models.CharField(blank=True, help_text='SMTP server', max_length=255)),
                ('email_port', models.IntegerField(default=587, help_text='SMTP port')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS for email')),
                ('mobile_api_enabled', models.BooleanField(default=True, help_text='Enable mobile API access')),
                ('mobile_api_rate_limit', models.IntegerField(default=100, help_text='API requests per hour per user')),
                ('auto_backup_enabled', models.BooleanField(default=True, help_text='Enable automatic backups')),
                ('backup_frequency_days', models.IntegerField(default=1, help_text='How often to backup (in days)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_production_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Settings',
                'verbose_name_plural': 'Production Settings',
            },
        ),
    ]
