# Generated by Django 5.2.7 on 2025-11-03 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_apikey_productionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Apakah user memiliki akses premium (permanent storage)'),
        ),
        migrations.CreateModel(
            name='PermanentScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_results_json', models.JSONField(help_text='Hasil scan lengkap dalam format JSON')),
                ('total_items', models.IntegerField(default=0, help_text='Total item yang ditemukan')),
                ('total_subdomains', models.IntegerField(default=0, help_text='Total subdomain yang ditemukan')),
                ('categories_detected', models.JSONField(default=dict, help_text='Kategori yang terdeteksi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_history', models.OneToOneField(help_text='Scan history yang terkait', on_delete=django.db.models.deletion.CASCADE, related_name='permanent_result', to='scanner.scanhistory')),
            ],
            options={
                'verbose_name': 'Permanent Scan Result',
                'verbose_name_plural': 'Permanent Scan Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserScanQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_limit', models.IntegerField(default=10, help_text='Total kuota scan yang tersedia (0 = unlimited)')),
                ('used_quota', models.IntegerField(default=0, help_text='Kuota yang sudah digunakan')),
                ('reset_period', models.CharField(choices=[('daily', 'Harian'), ('weekly', 'Mingguan'), ('monthly', 'Bulanan'), ('yearly', 'Tahunan'), ('never', 'Tidak pernah reset')], default='monthly', help_text='Periode reset kuota', max_length=20)),
                ('last_reset', models.DateTimeField(auto_now_add=True, help_text='Waktu reset terakhir')),
                ('next_reset', models.DateTimeField(blank=True, help_text='Waktu reset berikutnya', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User yang memiliki kuota ini', on_delete=django.db.models.deletion.CASCADE, related_name='scan_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Scan Quota',
                'verbose_name_plural': 'User Scan Quotas',
                'ordering': ['user__username'],
            },
        ),
    ]
