# Generated by Django 5.2.7 on 2025-11-07 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0015_customuser_is_premium_permanentscanresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Pesan feedback dari user')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Waktu feedback dibuat')),
                ('is_resolved', models.BooleanField(default=False, help_text='Apakah feedback sudah ditangani')),
                ('reply', models.TextField(blank=True, help_text='Balasan dari admin', null=True)),
                ('replied_at', models.DateTimeField(blank=True, help_text='Waktu admin membalas feedback', null=True)),
                ('replied_by', models.ForeignKey(blank=True, help_text='Admin yang membalas feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User yang memberikan feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
