# Generated by Django 5.2.7 on 2025-11-07 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0016_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama instansi/organisasi', max_length=200)),
                ('logo', models.ImageField(help_text='Logo instansi/organisasi', upload_to='partnerships/')),
                ('website_url', models.URLField(blank=True, help_text='URL website instansi (opsional)', null=True)),
                ('partnership_type', models.CharField(choices=[('partnership', 'Kerjasama'), ('sponsorship', 'Sponsorship')], default='partnership', help_text='Jenis kerjasama', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Apakah logo ditampilkan di footer')),
                ('display_order', models.IntegerField(default=0, help_text='Urutan tampilan (0 = pertama)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin yang menambahkan kerjasama', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partnerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partnership/Sponsorship',
                'verbose_name_plural': 'Partnerships/Sponsorships',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
