# Generated by Django 5.2.7 on 2025-11-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0018_scanresultitem_scansubdomain'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scanresultitem',
            new_name='scanner_sca_scan_hi_5ff1c3_idx',
            old_name='scanner_sca_scan_hi_idx',
        ),
        migrations.RenameIndex(
            model_name='scanresultitem',
            new_name='scanner_sca_scan_hi_0f2b6f_idx',
            old_name='scanner_sca_scan_hi_ver_idx',
        ),
        migrations.RenameIndex(
            model_name='scanresultitem',
            new_name='scanner_sca_url_fc5948_idx',
            old_name='scanner_sca_url_idx',
        ),
        migrations.RenameIndex(
            model_name='scanresultitem',
            new_name='scanner_sca_is_live_c6c944_idx',
            old_name='scanner_sca_is_live_idx',
        ),
        migrations.RenameIndex(
            model_name='scansubdomain',
            new_name='scanner_sca_scan_hi_0dfd8d_idx',
            old_name='scanner_sca_scan_hi_sta_idx',
        ),
        migrations.RenameIndex(
            model_name='scansubdomain',
            new_name='scanner_sca_subdoma_181119_idx',
            old_name='scanner_sca_subdoma_idx',
        ),
    ]
